### ISSUE TITLE
Several MPI libraries are loaded at the same time

### ISSUE THREAD

**Issue by hmt23** [arcaneframework/framework#180]
I installed Open MPI 4.1.1 via spack. Then I compile Arcane with it. It works fine, but
libarccore_message_passing_mpi.so are pointing to my system implementation (Open MPI 4.0.3).
I think this should not happen.
Do you have the same issues when you type `for f in $(ls *.so); do echo $f ; ldd $f | grep libmpi ; done`   on the lib directory after installing Arcane?

**Comment by cedricchevalier19** [comment]
I think it is the expected behavior for `CMake`: users should be able to choose their `interface` libraries, so by default `CMake` does not use `rpath` nor `runpath` for external libraries.

Spack explicitely sets CMake rpaths (https://spack-tutorial.readthedocs.io/en/latest/tutorial_buildsystems.html#cmake) :
```python
        # Set up CMake rpath
        args.extend([
            define('CMAKE_INSTALL_RPATH_USE_LINK_PATH', False),
            define('CMAKE_INSTALL_RPATH',
                   spack.build_environment.get_rpaths(pkg)),
            ...
```

You can try to configure the project with `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON` ([cmake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_RPATH_USE_LINK_PATH.html#variable:CMAKE_INSTALL_RPATH_USE_LINK_PATH)).

**Comment by hmt23** [comment]
Thank you, It solves my problem.
