### ISSUE TITLE
FindHDF5 does not work properly with static libraries

### ISSUE THREAD

**Issue by cedricchevalier19** [arcaneframework/framework#54]
According to https://alexreinking.com/blog/building-a-dual-shared-and-static-library-with-cmake.html, `find_package` should honor `BUILD_SHARED_LIBS`.

In the following test, https://github.com/arcaneframework/framework-ci/runs/4027731468?check_suite_focus=true , Arccon's findHDF5 finds a static library, and it does not work with Alien's dynamic library targets.

Other question: can `Arccore` work as static library ?

**Comment by grospelliergilles** [comment]
`HDF5` configuration is a bit tricky because there are multiple two to build HDF5 (with or without `cmake`).

For compatibility with versions without `cmake`, Arccon define several variables `HDF5_*` but there is no simple way to know the dependencies dependencies if `HDF5` is not compiled with `cmake`. To solve your problem, you should use the CMake variable `ARCCON_TARGET_HDF5`. If this variable is defined, use `add_library` with the value of this variable:

```{cmake}
if (DEFINED ARCCON_TARGET_HDF5)
  add_library(your_lib PUBLIC ${ARCCON_TARGET_HDF5})
else()
  # Use variable HDF5_*
endif()
```

**Comment by grospelliergilles** [comment]
It seems to work. I close the issue
